# Generated by Django 3.2.8 on 2021-10-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_or_video', models.FileField(upload_to='static/images')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('testimony', models.TextField()),
                ('image', models.ImageField(default='', upload_to='static/images')),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_or_video', models.FileField(upload_to='static/images')),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=300)),
                ('completed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ('-id',),
            },
        ),
    ]
