# Generated by Django 3.2.8 on 2021-10-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_or_video', models.FileField(upload_to='static/images')),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
