# Generated by Django 3.2.8 on 2021-10-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0003_auto_20211020_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='name',
        ),
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
