# Generated by Django 3.2.8 on 2021-10-20 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0004_auto_20211020_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image_or_video',
            field=models.FileField(upload_to='static/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'mp4', 'm4v'])]),
        ),
    ]
