# Generated by Django 3.2.8 on 2021-10-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0005_alter_projects_image_or_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image_or_video',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='projects',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/videos'),
        ),
    ]
