# Generated by Django 3.2.8 on 2021-10-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0006_auto_20211020_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos'),
        ),
    ]
