# Generated by Django 3.2.8 on 2021-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0007_auto_20211021_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
