# Generated by Django 3.2.8 on 2021-10-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0009_projectimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimages',
            options={'ordering': ('-id',), 'verbose_name_plural': 'ProjectsImages'},
        ),
    ]
