# Generated by Django 3.2.8 on 2021-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0011_alter_projectimages_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimages',
            options={},
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
