# Generated by Django 3.2.8 on 2021-10-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0012_auto_20211022_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architects.projects')),
            ],
        ),
    ]
