# Generated by Django 3.2.8 on 2021-10-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0014_auto_20211022_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='architects.projects'),
        ),
    ]
