# Generated by Django 3.2.8 on 2021-10-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0015_alter_projectimages_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimages',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architects.projects'),
        ),
    ]
