# Generated by Django 3.2.8 on 2022-01-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0019_alter_projectimages_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
